[project]
name = "tumblr-mass-blocker"
description = "A small GUI application that lets you mass block users from Tumblr posts."
readme = "README.md"
requires-python = ">= 3.14"
dependencies = [
  "Authlib",
  "httpx[brotli,http2,zstd]",
  "nicegui",
  "pythonnet @ git+https://github.com/pythonnet/pythonnet@python3.14",
  "pywebview",
  "winloop"
]
dynamic = ["version"]

[project.urls]
Funding = "https://ko-fi.com/maidscientistizutsumimarin"
Source = "https://github.com/MaidScientistIzutsumiMarin/tumblr-mass-blocker"

[project.scripts]
tumblr-mass-blocker = "tumblr_mass_blocker.__main__:main"

[project.optional-dependencies]
dev = ["pyinstaller"]

[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"
